### ISSUE TITLE
Importing <POP/POP.h> into the Swift bridging header does not seem to work

### ISSUE THREAD

**Issue by aleclarson** [facebook/pop#113]
When I put `#import <POP/POP.h>` in my `SwiftBridge.h`, I can't seem to reference any POP classes within my **.swift** files. Strangely, my target builds successfully despite many errors indicating `Use of undeclared type 'POP Class'` (with `POP Class` being a POP class of course).
- The same things happens on both Xcode 6 beta and Xcode 6 beta 2.
- The **pop.xcodeproj** is a sub-project inside of my own project
- POP is useable in Objective-C, but not in Swift
- Other headers I import in my `SwiftBridge.h` file can be used in Swift perfectly fine
- In both my project and target's **Build Settings**, I have **User Header Search Paths** set to find the POP headers and **Always Search User Paths** to `Yes`. **Framework Search Paths** and **Library Search Paths** both have nothing in them.
- `SwiftBridge.h` is correctly set under **Build Settings** as the **Objective-C Bridging Header** and **Install Objective-C Compatibility Header** is set to `Yes`.
- My project's target has its **Other Linker Flags** set to `-lc++ -all_load -ObjC`.
- The **pop** static library target is inside my target's **Target Dependencies** and the **libpop.a** is under **Link Binary With Libraries**.

Need any other information, just have to ask! :)

Thank you!

**Comment by Jpunt** [comment]
@aleclarson Both your question on StackOverflow and your workaround are 404's. Can you let us know how you fixed this?

**Comment by aleclarson** [comment]
@Jpunt It's been a long time since I've had this problem, so I don't remember what I had to do to fix this. Sorry!

**Comment by M0rph3v5** [comment]
For me it was actually related to importing pop like 

```
#import <pop/POP.h>
```

while 

```
#import <POP/POP.h>
```

fixed the errors I was having

**Comment by Jpunt** [comment]
Lol ;)

J.

**Comment by M0rph3v5** [comment]
ye ik was je al vaker tegengekomen, nu eindelijk achter gekomen waardoor
het kwam :P

2015-05-08 11:52 GMT-07:00 Jasper Haggenburg <notifications@github.com>:

**Comment by Heisenbean** [comment]
#import <POP/POP.h> still doesn't work :(

**Comment by tettoffensive** [comment]
I get a file not found for both `<pop/POP.h>` and `<POP/POP.h>`

(I'm using CocoaPods)

**Comment by tyjacobs** [comment]
I am having the same problem.  I'm using cocopods with Swift 2.0 and XCode 7.
I have tried both <pop/POP.h> and <POP/POP.h> with deep cleans between builds, and still get:

Use of unresolved identifier 'POPSpringAnimation' and
Use of unresolved identifier 'kPOPViewScaleXY'

Does anyone have a resolution for this?

**Comment by grantkemp** [comment]
Hi @tyjacobs, @tettoffensive  , I managed to get it working nicely with Swift 2.0 and Xcode 7. 

Here is what I did: 
After doing the Pod install: 
1. Open Workspace and clean
2. Create bridging header ->new file -> Object C  -> Save
3. In your Bridging header.h( emphasise that its  the **.h**) file put this in 
```
#import <pop/POP.h>
```
4. In your View Controller import statement put in this. 
```
import pop
```

Hope this helps. The documentation probably can be improved

**Comment by grantkemp** [comment]
Hi @tyjacobs, @tettoffensive  , I managed to get it working nicely with Swift 2.0 and Xcode 7. 

Here is what I did: 
After doing the Pod install: 
1. Open Workspace and clean
2. Create bridging header ->new file -> Object C  -> Save
3. In your Bridging header.h( emphasise that its  the **.h**) file put this in 
```
#import <pop/POP.h>
```
4. In your View Controller import statement put in this. 
```
import pop
```

Hope this helps. The documentation probably can be improved

**Comment by grantkemp** [comment]
Hi @tyjacobs, @tettoffensive  , I managed to get it working nicely with Swift 2.0 and Xcode 7. 

Here is what I did: 
After doing the Pod install: 
1. Open Workspace and clean
2. Create bridging header ->new file -> Object C  -> Save
3. In your Bridging header.h( emphasise that its  the **.h**) file put this in 
```
#import <pop/POP.h>
```
4. In your View Controller import statement put in this. 
```
import pop
```

Hope this helps. The documentation probably can be improved

**Comment by igorkurylenko** [comment]
I did it step by step in Xcode 7.2. It doesn't work.

**Comment by marklin2012** [comment]
I did it step by step in Xcode 7.2 as well.But it doesn't work.

**Comment by LSnail** [comment]
@grantkemp

**Comment by LSnail** [comment]
@grantkemp  I did `import pop` and it works perfectly. Thank you so much!
