### ISSUE TITLE
PopDefines.h not found

### ISSUE THREAD

**Issue by azamsharp** [facebook/pop#116]
I just downloaded the source code for Pop and dragged the pop folder in my Objective-C project Single View Application project.

When I build I get the following error: 

/Users/azamsharp/Documents/Projects/FacebookPopDemo/FacebookPopDemo/pop/POPAnimationExtras.h:12:9: 'POP/POPDefines.h' file not found 

Any ideas!

**Comment by grantkemp** [comment]
I get this error even through cocoapods

**Comment by tangamampilia** [comment]
I'm getting this error with CocoaPods also.

**Comment by tangamampilia** [comment]
Worked again after clearing the derived data.

**Comment by cqzhlei** [comment]
you should set your project correctly!
1、in the **build setting** search **search user**
     
![correct setting](https://cloud.githubusercontent.com/assets/8794512/17207723/6ffadedc-54e8-11e6-88c4-193fe6c5e6fe.png)
set like this

2、in your pch file
![correct setting](https://cloud.githubusercontent.com/assets/8794512/17207764/9dca9c08-54e8-11e6-93aa-5209dd1e0927.png)

 i  cant write english fluently. sorry!!

**Comment by kos9kus** [comment]
The following link to compile a universal framework for iOS
https://gist.github.com/kos9kus/bc63a2b81f4e8bcc23e4c7cbcacf9452
