### ISSUE TITLE
Why doesn't POPDecayAnimation use toValue?

### ISSUE THREAD

**Issue by callmeed** [facebook/pop#13]
I noticed that POPDecayAnimation ignores the toValue property when set (fromValue works great). Why is this? 

If, for example, I'm using POPDecayAnimation to animate an X or Y position, what would be the appropriate way to have my object animate to a specific coordinate?

**Comment by pronebird** [comment]
Anyone managed to do the reverse math for velocity/deceleration based on target position? I have a hard time with formulas here :/

**Comment by hfossli** [comment]
If POPDecayAnimation is just following standard deceleration rules this method should give you the acceleration/deceleration for the desired distance and velocity. 
```
+ (CGFloat)decelerationForDistance:(CGFloat)distance withVelocity:(CGFloat)velocity
{
    if(distance == 0.0)
    {
        return 0.0;
    }
    if(velocity == 0.0)
    {
        return 0.0;
    }

    CGFloat acceleration = ((velocity * velocity)) / (distance * 2.0);
    CGFloat deceleration = 1.0 / (abs(acceleration) / 1000.0);
    return MIN(0.95, MAX(0.0, deceleration));
}
```

**Comment by pronebird** [comment]
@hfossli ah now I see, I had some issues adapting calculated acceleration to deceleration.

I put together a sample app here based on your function:
https://gist.github.com/pronebird/f62330a395712c41feaa

So basically I want to move my from point A (0, 0) to point B (100, 0)  with initial velocity = (50, 0). 

So we have:

distance = 100 units
acceleration = 12.5
deceleration factor = 0.999

POP calculated coordinate is: 44.956

decay = <POPDecayAnimation:0x79d03ed0; from = (0.000, 0.000); to = (44.956, 0.000); velocity = (50.000, 0.000); duration = 2.301463; deceleration = 0.999000>

**Comment by hfossli** [comment]
Well, my attempt was garbage. Seems like the formulas are quite more complicated looking at the `POPDecayAnimationInternal.h`. I guess what's complicating this is the rest/threshold-concept.
