### ISSUE TITLE
Custom POPAnimatableProperty in Swift?

### ISSUE THREAD

**Issue by aleclarson** [facebook/pop#133]
Any animation that uses my custom property stops immediately after it starts. This results in appearing as if no animation was ever started. Below is how I define my custom property in Swift.

````Swift
var myCustomProperties = [String:POPAnimatableProperty]()

let kPOPCustom: String = {
  let value = "abc.kPOPCustom"
  
  myCustomProperties[value] = POPAnimatableProperty(name: value, initializer: {
    $0.readBlock = {
      $1[0] = (obj as MyCustomClass).myCustomProperty
    }
    $0.writeBlock = {
      (obj as MyCustomClass).myCustomProperty = $1[0]
    }
  })

  return value
}()
````
Not sure if it's important, but `MyCustomClass` is a Swift class. Does it need to have `@objc` or inherit from an Objective-C class in order to be animated with POP?

Any questions, please ask! :smile:

**Comment by erudenko** [comment]
Unfortunately your link is not working

**Comment by aleclarson** [comment]
@erudenko This was a while ago, and the problem fixed itself after I did some stuff that I don't remember anymore. Sorry I couldn't help you out.

**Comment by wjf3** [comment]
Since Pop assumes that views that it’s called on implement -transform to handle manipulation like scaling the view, but SpriteKit doesn’t (it has its own -scaleBy method), trying to make a custom property that just gives me the raw values to plug in myself:

 self.property = POPAnimatableProperty.propertyWithName("scale", initializer: {
        (property: POPMutableAnimatableProperty) -> Void in
        
        property.readBlock = {(object: AnyObject!, inout values: Array<CGFloat>) -> Void in
          values[0] = (object as! SKNode).xScale
        }
        
        property.writeBlock = {(object: AnyObject!, inout values: UnsafePointer<CGFloat>) -> Void in
          (object as! SKNode).setScale(values[0])
        }
        
      }) as! POPAnimatableProperty

keeps on giving me "cannot assign a value of type POPAnimatableProperty to a value of type POPAnimatableProperty! error and whenever I try and rejigger things around something new comes up. Pretty new to swift and any help here would be amazing. Thanks!

**Comment by marcioadr88** [comment]
@wjf3 this code worked for me:

```swift
    func togglePopAnimation(on: Bool) {
        var animation: POPSpringAnimation? = self.pop_animationForKey("popAnimation") as? POPSpringAnimation
        
        if animation == nil {
            animation = POPSpringAnimation()
            animation!.springBounciness = 10
            animation!.springSpeed = 100
            
            animation!.property = POPAnimatableProperty.propertyWithName("popAnimationProgress", initializer: propertyInitializer) as! POPAnimatableProperty
            
            self.pop_addAnimation(animation, forKey: "popAnimation")
        }
        
        animation!.toValue = on ? 1.0 : 0.0
    }
    
    func propertyInitializer(prop: POPMutableAnimatableProperty!) {
        prop.readBlock = { objc, values in
            values[0] = (objc as! BotonRedSocial).popAnimationProgress
        }
        
        prop.writeBlock = { obj, values in
            (obj as! BotonRedSocial).popAnimationProgress = values[0]
        }
        
        prop.threshold = 0.001
    }
```

**Comment by warpling** [comment]
Could not for the life of me figure out what was going on. Ended up creating an animation driver object to power this based on @aleclarson's observation to make this work. Roughly something like this… (haven't tested)
```Swift
class SwiftViewAnimator : NSObject {

    public weak var view: UIView?

    func animatableProperty() -> POPAnimatableProperty? {
        return POPAnimatableProperty.property(withName: "property", initializer: { prop in
            guard let prop = prop else {
                return
            }
            // read value
            prop.readBlock = { obj, values in
                guard let view = obj as? UIView,
                    let values = values else {
                        return
                }

                values[0] = CGFloat(view.customProperty)
            }
            // write value
            prop.writeBlock = { obj, values in
                guard let view = obj as? UIView,
                    let values = values else {
                        return
                }

                view.customProperty = CGFloat(values[0])
            }
            // dynamics threshold
            prop.threshold = 0.01
        }) as? POPAnimatableProperty
    }
}

class CustomView : UIView {
    var animator = SwiftViewAnimator()
    var customProperty: CGFloat
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        animator.view = self
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}
```

```Swift
        let customAnimation = POPBasicAnimation()
        customAnimation.property = customView.animator.animatableProperty()
        customAnimation.fromValue = 0.0
        customAnimation.toValue = 1.0
        customAnimation.duration = 1.0
        customView.animator.pop_add(customAnimation, forKey: "test")

```
