### ISSUE TITLE
Impossible to animate kPOPLayerRotationY more than 90 degrees

### ISSUE THREAD

**Issue by wircho** [facebook/pop#155]
This issue is very simple to reproduce:

    POPBasicAnimation *animation = [POPBasicAnimation animationWithPropertyNamed:kPOPLayerRotationY];
    animation.fromValue = @0;
    animation.toValue = @1.9;
    animation.duration = 1;
    [view.layer pop_addAnimation:animation forKey:@"key"];

**Comment by kimon** [comment]
Dupe of https://github.com/facebook/pop/issues/71
