### ISSUE TITLE
POPVector.h and PopVector.mm throws error "Lexical or Preprocessor issue"

### ISSUE THREAD

**Issue by Manojraj** [facebook/pop#159]
I have got the following errors when i tried to integrate pop with my project 

PopVector.h
 Lexical or Preprocessor issue
Too many arguments provided to function-like macro invocation
In file included from /pop/PopVector.mm:10:
Macro 'NSCAssert' defined here

POPVector.mm
 Lexical or Preprocessor issue
Too many arguments provided to function-like macro invocation
 Lexical or Preprocessor issue
Too many arguments provided to function-like macro invocation

**Comment by kimon** [comment]
Glad to hear this was resolved!
