### ISSUE TITLE
Cocoapods Unable to find a specification for 'pop (~> 1.0)'

### ISSUE THREAD

**Issue by jkou** [facebook/pop#161]
I bought a new mac and it gave me this error when I run "pod instal"l

 Unable to find a specification for 'pop (~> 1.0)'

So I install the pop.podspec on my mac. But this file did not pass the validation when I run "pod spec lint pop.podspec"

**Comment by kimon** [comment]
Good workaround, though it shouldn't be necessary. Have other people been experiencing this as well?

**Comment by pronebird** [comment]
How about `pod repo update` and then `pod search pop`?

**Comment by facebook-github-bot-1** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by YifangZhang** [comment]
well, isnt it still open? Is the problem solved? I am facing the same issue right now...

**Comment by grp** [comment]
Hard to say why this is happening — I'd suggest filing an issue on the Cocoapods repo since it seems more related to that (I don't see anything wrong in the Pop podspec myself).
