### ISSUE TITLE
File not Found; support case sensitive filesystems

### ISSUE THREAD

**Issue by ghost** [facebook/pop#167]
Guy's, 

when the pod is checked out from the cocoa pods repository the folder created is small case. "pop"
in your headers you refer to the framework as it being uppercase "POP"
Building on a case sensitive server drive partition, that just does not work.

Regards.

**Comment by facebook-github-bot-1** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by grantkemp** [comment]
This is still broken on latest cocoapods version. I get the following error: 
<pop/POPDefines.h> file not found

**Comment by nlutsenko** [comment]
Looks like this is resolved on the latest master as well as on the latest release `1.0.9`.
We don't have any usages of uppercase `<pop/` in the codebase at this moment.
Please open a new issue with repro steps (if we can't reproduce an issue - it means there is not really a way to fix it) if you are running into any problems.
