### ISSUE TITLE
Undefined symbols for architecture armv7: _kPOPViewFrame

### ISSUE THREAD

**Issue by OxidBurn** [facebook/pop#170]
Please help with this issue. After updating pop pods got those errors:

http://joxi.ru/Aq8tVP3JTJBtaygjzlo

**Comment by kimon** [comment]
Cocoapods appears to have had a few minor releases where linker flags were not being properly added to settings. See https://github.com/facebook/pop/issues/173 for workaround. Please re-open if you're encountering with latest version of Cocoapods.

**Comment by yupliang** [comment]
i also meet the same problem right now, delete this folder helped me.
```
~/Library/Developer/Xcode/DerivedData/ModuleCache
```
