### ISSUE TITLE
Ignoring to value on decay animation 

### ISSUE THREAD

**Issue by devnikor** [facebook/pop#203]
When use `POPDecayAnimation` in Swift app to animate view I get following message:
`ignoring to value on decay animation <POPDecayAnimation:0x7f87a1dd3c40; from = null; to = null; deceleration = 0.998000>`
But `POPSpringAnimation` works correctly.
There are a problem code:
```    
var frame = from!.view.frame
frame.origin.y += frame.size.height
var animation = POPDecayAnimation()
animation.property = POPAnimatableProperty.propertyWithName(kPOPViewFrame) as POPAnimatableProperty
animation.toValue = NSValue(CGRect:frame)
animation.completionBlock = {
    (_, _) in
    self.trulySwitchViewController(from, toViewController: nil)
}
from!.view.pop_addAnimation(animation, forKey: "dropDown")```

**Comment by kimon** [comment]
The decay animation takes an initial velocity as input. You can also specify fromValue and deceleration.

**Comment by devnikor** [comment]
Same problem with `animation.velocity = 10`
