### ISSUE TITLE
custom property for CGAffineTransform

### ISSUE THREAD

**Issue by golopupinsky** [facebook/pop#205]
Hi. I'm trying to animate view's ```CGAffineTransform```.
I created custom property but I can't animate it. 
"Unsuported value" exception is thrown in ```POPUnbox```. That seems weird to me. 
POPValueType enum defines ```kPOPValueAffineTransform```. Doesn't that mean affine transforms are supposed to be animatable?

**Comment by kimon** [comment]
Affine transforms are not animatable as a whole. You can however animate subcomponents of a transform (e.g. kPOPLayerRotation*, kPOPLayerScale* etc)

**Comment by liuzhiyi1992** [comment]
but unsupport CATransform3D too, "Unsuported value" with "+ valueWithCATransform3D:"

**Comment by grp** [comment]
For that, you can also animate subcomponents of the transform, like `kPOPLayerRotationY` or whatever you need.

**Comment by liuzhiyi1992** [comment]
@grp thanks!
