### ISSUE TITLE
Threshold property in POPAnimatableProperty doesn't work?

### ISSUE THREAD

**Issue by LJJ** [facebook/pop#206]
I set POPAnimatableProperty like this:

 POPAnimatableProperty * aprop = [POPAnimatableProperty propertyWithName:@"count" initializer:^(POPMutableAnimatableProperty *prop) {
        prop.readBlock = ^(id obj, CGFloat values[]) {
            values[0] = [[obj description] floatValue];
        };
        prop.writeBlock = ^(UILabel *obj, const CGFloat values[]) {
            [obj setText:[NSString stringWithFormat:@"%.1f",values[0]]];
        };
        prop.threshold = 1.0;
    }];

but it has no difference to threshold=0.1, I still can see the change after decimal point.

**Comment by grp** [comment]
The threshold refers to when an animation completes. For some animation types, like decay and spring, the animation value will never exactly equal the `toValue`. To avoid endlessly getting closer but never reaching the target, the animation will complete once it's within `threshold` of the `toValue`.

So `threshold` is not a general-purpose way of limiting the values assigned to the property. If you want that, you can do the rounding within your `writeBlock`.

**Comment by LJJ** [comment]
@grp I find I misunderstand the meaning of threshold. It does work like you said. Thank you very much!
