### ISSUE TITLE
Do Pop animations support fillMode?

### ISSUE THREAD

**Issue by warpling** [facebook/pop#216]
I have an animation with a delayed `beginTime` that needs a `fillMode` to avoid jerkiness.
Maybe I'm just bleary-eyed and tired, but I can't seem to find it.

**Comment by kimon** [comment]
There is no `fillMode` property, but you should be able to simply set the initial property value to easily emulate the effect. Were you able to track down the UI glitch you were seeing?

**Comment by warpling** [comment]
The problem is that I don't want to be at the `fromValue` until the time when the animation actually starts :confused:. Using a delay that sets the initial property and then adds the animation without setting the `beginTime` works but is kind of hacky :/

Would it be possible to add `fillMode` to Pop animations? I can't think of a reason it wouldn't be…

**Comment by warpling** [comment]
Hey @kimon thoughts on how fillMode could be added? Might be above my skill level, but I'm curious if there are any immediate hurdles to contend with. This is the main reason not all of my CAAnimations are POPAnimations.
