### ISSUE TITLE
xCode 6.3 Beta warning: Semantic issue

### ISSUE THREAD

**Issue by steilerDev** [facebook/pop#217]
When using pop within a SWIFT project (installed using cocoa pods pre build) xCode 6.3 beta issues three warnings about the same function: 

`POPDecayAnimationInternal.h:61:11: Absolute value function 'fabsf' given an argument of type 'const CGFloat' (aka 'const double') but has parameter of type 'float' which may cause truncation of value`

`POPSpringAnimationInternal.h:49:67: Absolute value function 'fabsf' given an argument of type 'double' but has parameter of type 'float' which may cause truncation of value`

`POPSpringAnimationInternal.h:49:67: Absolute value function 'fabsf' given an argument of type 'double' but has parameter of type 'float' which may cause truncation of value`

xCode suggests to replace the `fabsf` function with `std::abs`. Unfortunately I am very new to iOS development, so I can not guarantee that this replacement would change any behaviour within the application.

**Comment by pronebird** [comment]
I can suggest that this happens because CGFloat is double on 64bit and float on 32bit. Would be probably better to use tgmath or something that provides macro to handle that.

**Comment by kimon** [comment]
All known Xcode 6.3 beta warnings should be fixed on Pop master. Try things out by making the following be your pop entry in your Podfile:

`
pod 'pop', :git => 'https://github.com/facebook/pop.git'
`

**Comment by AdulteTerrible** [comment]
Same issue here, but with xCode 6.3 release.
I've pulled the latest version of Pop. The .xcodeproj fails to build due to the exact same issues mentionned by stellerDev.
Any suggestion?

**Comment by AdulteTerrible** [comment]
Turns out calling fabs() instead of fabsf() does the trick!

**Comment by steilerDev** [comment]
I used the suggested `std::abs` functions and used `#import <cmath>` to remove the error of an ambiguous call to `std::abs`.

**Comment by medington** [comment]
> All known Xcode 6.3 beta warnings should be fixed on Pop master. Try things out by making the following be your pop entry in your Podfile:

Will this be released in a podspec anytime soon?
