### ISSUE TITLE
POPDecayAnimation does not work when scaling

### ISSUE THREAD

**Issue by pronebird** [facebook/pop#221]
Can I use POPDecayAnimation to scale layer from 0 to 1 and back? 

I tried the code below but there is no animation, the layer is fully visible. Also if I use single Number for velocity which I'd expect to be the same as using CGSize, then I don't see anything on screen at all.

```objective-c
POPDecayAnimation* decay = [POPDecayAnimation animationWithPropertyNamed:kPOPLayerScaleXY];

decay.velocity = [NSValue valueWithCGSize:CGSizeMake(0.2, 0.2)];
decay.deceleration = 0.1;
decay.repeatForever = YES;
    
[circleLayer pop_addAnimation:decay forKey:@"scale"];
```

**Comment by lightice11** [comment]
What about trying a `CGPoint` instead? I had a similar problem of the screen turning black while I was using a `POPSpringAnimation` with `kPOPLayerScaleXY`.

**Comment by pronebird** [comment]
Thanks @lightice11. That was it, dunno why I used `CGSize`.
