### ISSUE TITLE
Recommendation for "transitionDuration" value with custom view controller transitions?

### ISSUE THREAD

**Issue by christianselig** [facebook/pop#222]
Seeking to use POP for custom view controller transitions, but it's required to implement `- (NSTimeInterval)transitionDuration` in the `UIViewControllerAnimatedTransitioning` delegate. With spring animations and the like, you obviously don't set a duration; the values you set for the spring dictate the duration.

Any recommendations for what I should put for duration? Manually time the length of the spring?

**Comment by grp** [comment]
I would suggest putting 0, since you aren't going to use the animations that UIViewController sets up by default. If you put something nonzero, it's going to start an animation of that duration that would probably just get in the way of the Pop animation.

**Comment by pronebird** [comment]
@grp this may result in certain appearance events to be delivered before pop animations finished, which in certain cases can blow up, plus transitionCoordinator wouldn't work either.

**Comment by kimon** [comment]
@pronebird @christianselig @grp's suggestion of 0 duration sounds like a good approach. if there is application logic that can't handle events during animation, that seems like a limitation that might be relatively easy (and valuable to the end-user) to overcome.
