### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by LinusU** [facebook/pop#223]
It would be great if pop was installable thru [Carthage](https://github.com/Carthage/Carthage).

Carthage is a tool for easily depending on dynamic frameworks and thus only works for iOS 8 and newer. I personally find it much better than CocoaPods since it dosen't do any magic and just provides the framework files for me.

It currently only builds the mac framework and not the one for iOS. I'm not familiar with the internals enough to be able to say why but hopefully it isn't too hard to fix.

Example `Cartfile`:

```text
github "facebook/pop" ~> 1.0.7
```

**Comment by grp** [comment]
I don't think we're going to support this. We generally prefer to specify build configuration in human-readable files, rather than the opaque blob generated by Xcode. We also prefer source dependencies rather than binary, so you can easily verify exactly which code is included in your app and build for new architectures.

**Comment by Francescu** [comment]
@grp 
I think Carthage builds a framework from the sources pulled in local. 

It doesn't perform any magic like cocoapods, it just:
1. Resolved dependencies
2. Fetch and get sources
3. Build it into framework

Then the developers can integrate the framework into their Xcode project.

**Comment by rosskimes** [comment]
Adding another vote for Carthage support.

**Comment by grp** [comment]
@Francescu @rosskimes In general, it's hard to maintain the opaque Xcode project needed for Carthage support. For Cocoapods, the build setup is written in a human readable format, so it's a lot easier to maintain.

**Comment by pawlowskialex** [comment]
It's really not that hard, you can still use all that xcconfig hierarchy, etc. If it's really that required (though I'm yet to see anyone ever actually using those).
But, frankly, most of those configs just doesn't make any sense anymore and they're heavy iOS-biased like Project.xcconfig defining SDKROOT = iphoneos for ALL targets, as if OS X doesn't even exist.
Produced OS X framework is completely corrupted: broken symlinks, no headers, dylib install path is local absolute path. It just doesn't work.

Right now that xcodeproj is little more than a list of project files and somewhat convenient way to run tests. There's just no way to use pop beyond CocoaPods as of yet.

So, uh, besides this somewhat "philosophical" dispute, there's no real reason to not support Carthage. For CocoaPods users nothing would change. 
We just need to restructure the project into nice iOS Static Lib/iOS Framework/Mac Framework targets that actually produce meaningful builds, I've actually done most of the work in my private fork, for one of our Mac apps that doesn't use CocoaPods.

I can contribute my changes if you want.

**Comment by LinusU** [comment]
@pawlowskialex I would love to see your changes merged, and I don't see any downside with it.

**Comment by grp** [comment]
I tried cleaning up the Xcode project some in 9e44015664c5d6b8c8b21c0f8344633f8cec8b08. I'm not sure what else needs to change for Carthage support, though.

**Comment by julien-c** [comment]
I'd be really interested in this as well.

**Comment by blommegard** [comment]
master seems to work just fine after the cleanup in 9e44015.

**Comment by JosaphatRJG** [comment]
I have this error when I execute "carthage update"
![image](https://user-images.githubusercontent.com/36025292/42321934-2b4808d4-8063-11e8-8382-1f6083cea24f.png)
