### ISSUE TITLE
 Is there a way to allow user scroll action during an POPBasicAnimation(kPOPScrollViewContentOffset)?

### ISSUE THREAD

**Issue by willbin** [facebook/pop#231]
Here I add one `kPOPScrollViewContentOffset` animation to `UIScrollview` as follows:

    POPBasicAnimation *scaleAnimation = [POPBasicAnimation animationWithPropertyNamed:kPOPScrollViewContentOffset];
    scaleAnimation.timingFunction = [CAMediaTimingFunction functionWithName:kCAMediaTimingFunctionLinear];
    scaleAnimation.fromValue = aFromValue;
    scaleAnimation.toValue = aToValue;
    scaleAnimation.autoreverses = YES;
    scaleAnimation.repeatForever = YES;
    scaleAnimation.duration = timeLength;
    [topScrollView pop_addAnimation:scaleAnimation forKey:@"OffsetAnimation"];
            
But when I scroll this UIScrollview with my finger, there is no response.
In UIView animation, there is a option called: `UIViewAnimationOptionAllowUserInteraction` that allow user action while animating.

So is there a way to allow my scroll action during an POPBasicAnimation?
ps:I have stackoverflowed, nothing useful founded.

**Comment by grp** [comment]
The easiest way to support that is to recognize when scrolling starts, and remove the Pop animation. The `-[UIScrollViewDelegate scrollViewWillBeginDragging:]` method should be useful for that.

**Comment by willbin** [comment]
http://meijiapp.com/post/f036b8be5a26d484963d1deba81c3146
@grp You can have a look at my web page.
This is what I will do in my app.

**Comment by willbin** [comment]
Done!
Add codes here.


    - (void)scrollViewWillBeginDragging:(UIScrollView *)scrollView
	// called on finger up if the user dragged. velocity is in points/millisecond. targetContentOffset may be changed to adjust where the scroll view comes to rest
	{
    	TJScrollView *topScrollView = [self getCurrentScrollView];
    	if (scrollView == topScrollView)
    	{
      	  [topScrollView pop_removeAllAnimations];
    	}
	}
	
@grp Thanks a lot.

**Comment by grp** [comment]
Cool, glad it worked! (And sorry I missed this for a few months.)
