### ISSUE TITLE
Animations not adhering to "Slow Animations" setting on simulator

### ISSUE THREAD

**Issue by krisanthony** [facebook/pop#233]
POPBasicAnimation *animIn = [POPBasicAnimation animationWithPropertyNamed:kPOPLayerOpacity];
    animIn.toValue = @(1);
    animIn.timingFunction = [CAMediaTimingFunction functionWithName:kCAMediaTimingFunctionEaseOut];
    animIn.duration = .15f;
    [_poppedOutCell.layer pop_addAnimation:anim forKey:@"animIn"];

Using a simple animation such as above, nothing tricky. Animations will be the same speed regardless of the setting.

I see that the animations are meant to adhere to the setting. Anyone else seeing this?

**Comment by kimon** [comment]
Should be fixed on master. Until we have a new release, you can update your Podfile: https://github.com/facebook/pop#installation

**Comment by kimon** [comment]
Will keep open until release.

**Comment by krisrudolph** [comment]
oh great thanks!

**Comment by facebook-github-bot-1** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by grp** [comment]
Should be released by now. :)
