### ISSUE TITLE
Flip animation

### ISSUE THREAD

**Issue by nderkach** [facebook/pop#234]
How would I go about doing a flip animation with pop?

Is the something similar to UIViewAnimationTransitionFlipFromRight? Are there any benefits of using pop  animation in this case, rather than stock UIView animations?

**Comment by palcalde** [comment]
Check : https://github.com/schneiderandre/popping. Look at FoldingViewController.

**Comment by nderkach** [comment]
So, you can do a rotation with `kPOPLayerRotationY`. Unfortunately, there is a bug #71 which prevents you from rotating for more than M_PI/2

**Comment by grp** [comment]
Thanks @nderkach, this is pretty close to a duplicate of #71 for flips in that direction.
