### ISSUE TITLE
kPOPViewScaleXY issue when view's scale set to [0.0, 0.0] to start

### ISSUE THREAD

**Issue by flyosity** [facebook/pop#24]
Hey guys, I've been trying to animate a button's scale from 0.0 to 1.0 all evening and I think I may have ran into an issue.

What I'm trying to accomplish is to add a button to my view hierarchy with a 0.0 (invisibly small) scale to start, and then animate it up to 1.0 so it bounces into view on the screen. Here's what my code looks like

```
// Boring boilerplate code to create a button and add to a view, then...
myButton.transform = CGAffineTransformMakeScale(0.0, 0.0);

POPSpringAnimation *animation = [POPSpringAnimation animation];
animation.property = [POPAnimatableProperty propertyWithName:kPOPViewScaleXY];
animation.fromValue = [NSValue valueWithCGPoint:CGPointMake(0.0f, 0.0f)];
animation.toValue = [NSValue valueWithCGPoint:CGPointMake(1.0f, 1.0f)];
animation.springBounciness = 20.0f;
animation.springSpeed = 3.0f;
[myButton pop_addAnimation:animation forKey:@"bounce"];
```

So this code doesn't work, the button stays at 0.0 scale. In fact it doesn't matter what I set as my fromValue and toValue if I set the initial transform to a [0.0, 0.0] scale. If I don't set the initial scale to 0.0 then it works and I can animate the button, but that defeats the purpose since I want the button to be at 0.0 scale as it lands in the view hierarchy, then animate from 0.0 to 1.0 so its initial appearance is bouncy and delightful.

What I've found is if I set my initial scale to something extremely small, but non-zero (like CGAffineTransformMakeScale(0.001, 0.001)) then it'll work nicely. It seems there's an issue with a layer's initial transform scale being 0 vs. a non-zero number and the interpolation Pop provides to scale it up to the toValue.

I'm extremely new to Pop (as I'm sure many people are today!) so please let me know if I'm missing something trivial or not using the framework in a common manner.

Thanks!
Mike

**Comment by SRandazzo** [comment]
Ran into this and the above was helpful! Wanted to add an additional case for those who find it in the future:

When animating using a POPSpringAnimation, the spirngyness causes the scale to go below (0,0), which inverts things as described above.

To remedy this, you can apply a `clampMode` to prevent it from dipping below 0,0

thanks!

**Comment by jocelynzz** [comment]
Hi my codes happen to be exactly the same as @flyosity and I try to achieve the effect that a view will 'scale to appear', with a bouncy effect in the end. I changed 0.0 to 0.01 but it seems that I can only see the bouncy effect but not the 'scale to effect' one. Any suggestions?

**Comment by ISMeSAM** [comment]
不明觉厉
