### ISSUE TITLE
Big UITableView Animation

### ISSUE THREAD

**Issue by oleynikd** [facebook/pop#240]
Hi,
I need help. I'm trying to animate `UITableView` with pop. Here's the working demo:
https://www.dropbox.com/s/z3b9vk8nyoxtzd7/PopUITableViewDropDownAnimation.mov?dl=0

Animation is very smooth when it goes down. Maybe it is hard to see on video (because of airplay) but when main `UITableView` **goes up** animation is not smooth at all (feels like ~18fps)... When I tried it on some 'old' hardware like iPad 2 - it is just awful! Feels like 5 fps. Again - down animation is very smooth every time, the problem is only with the up one.

I've seen that in Paper app animations are very smooth even when animating pretty big tables.
How can I optimise this animation?
Thanks.

**Comment by oleynikd** [comment]
Here's the video of iPad 2: https://dl.dropboxusercontent.com/u/14522796/PopUITableViewDropDownAnimation.iPad.mov

**Comment by darknoon** [comment]
Depends on why it's slow. Can you attach an instruments trace of the issue?

**Comment by liuxuan30** [comment]
Try use instrument and find some articles on how to identify why it's slow. Too many reaons can cause slow. e.g. off-screen rendering, main queue is busy. UITableView is reusing cells, and you said down animation is smooth but up is slow, might check the logic what's the difference while up and down?

**Comment by oleynikd** [comment]
Thank you guys for reply!

Here's the Time Profiler Track export excluding system libraries: https://dl.dropboxusercontent.com/u/14522796/Time%20Profiler%20-%20FreeTV_Run1.csv

As I could understand the heaviest trace is down to [EPG getCurrentEPGForChannel:] so I need to dig here how to optimise this method's performance that is a part of cell render, right?

**Comment by liuxuan30** [comment]
no ideas what is [EPG getCurrentEPGForChannel:], sorry cannot offer help.
