### ISSUE TITLE
pop doesn't build in Xcode 7 because OCUnit has been deprecated

### ISSUE THREAD

**Issue by 4chanmoot** [facebook/pop#243]
My current version is:

commit 038f29b2de47db3fce803c5a180eee604ebe1977
Merge: 447f408 95c21b8
Author: Grant Paul <github@grantpaul.com>
Date:   Sat Apr 18 12:47:49 2015 -0700

**Comment by grp** [comment]
Are you using Cocoapods or the Xcode project for Pop? For Cocoapods, it should be fully on XCTest, but it looks like the Xcode project still references SenTestingKit.framework in a few places. (I'll look into fixing that ASAP.)

**Comment by grp** [comment]
Thanks @b3ll!
