### ISSUE TITLE
Import statement in readme is wrong

### ISSUE THREAD

**Issue by thomasdegry** [facebook/pop#249]
After installing Pop using cocoapods in a swift project and including it in my bridging header like this: `#import <pop/POP.h>`, the project doesn't compile (like referenced in the readme). Only works when having it like this: `#import <Pop/Pop.h>`, Can someone confirm? I can submit a PR to update the readme

**Comment by grp** [comment]
The name of the pod is `pop` in the Podspec, so I think `#import <pop/POP.h>` should be correct. It may be different for Swift, however.
