### ISSUE TITLE
Undefined symbols for architecture arm64:

### ISSUE THREAD

**Issue by magin** [facebook/pop#25]
I'm integrating POP with CocoaPods.

Undefined symbols for architecture arm64:
  "___dynamic_cast", referenced from:
      applyAnimationTime(objc_object_, _POPAnimationState_, double) in libPods.a(POPAnimator.o)
      applyAnimationProgress(objc_object_, _POPAnimationState_, double) in libPods.a(POPAnimator.o)
  "vtable for __cxxabiv1::__si_class_type_info", referenced from:
      typeinfo for _POPPropertyAnimationState in libPods.a(POPSpringAnimation.o)
      typeinfo for _POPSpringAnimationState in libPods.a(POPSpringAnimation.o)
      typeinfo for std::__1::__shared_ptr_pointer<POP::Vector*, std::__1::default_delete<POP::Vector>, std::__1::allocatorPOP::Vector > in libPods.a(POPSpringAnimation.o)
      typeinfo for std::__1::__shared_ptr_pointer<POPAnimatorItem*, std::__1::default_delete<POPAnimatorItem>, std::__1::allocator<POPAnimatorItem> > in libPods.a(POPAnimator.o)
      typeinfo for _POPBasicAnimationState in libPods.a(POPBasicAnimation.o)
      typeinfo for _POPDecayAnimationState in libPods.a(POPDecayAnimation.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for std::__1::__shared_count", referenced from:
      std::__1::shared_ptrPOP::Vector::shared_ptr<POP::Vector, void>(POP::Vector_) in libPods.a(POPSpringAnimation.o)
      std::__1::shared_ptr<POPAnimatorItem>::shared_ptr<POPAnimatorItem, void>(POPAnimatorItem_) in libPods.a(POPAnimator.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for std::__1::__shared_weak_count", referenced from:
      std::__1::shared_ptrPOP::Vector::shared_ptr<POP::Vector, void>(POP::Vector_) in libPods.a(POPSpringAnimation.o)
      std::__1::shared_ptr<POPAnimatorItem>::shared_ptr<POPAnimatorItem, void>(POPAnimatorItem_) in libPods.a(POPAnimator.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "std::__1::__shared_weak_count::__add_shared()", referenced from:
      -[POPSpringAnimation velocity] in libPods.a(POPSpringAnimation.o)
      -[POPSpringAnimation setVelocity:] in libPods.a(POPSpringAnimation.o)
      _POPPropertyAnimationState::willRun(bool, objc_object_) in libPods.a(POPSpringAnimation.o)
      _POPSpringAnimationState::advance(double, double, objc_object_) in libPods.a(POPSpringAnimation.o)
      _POPPropertyAnimationState::computeProgress() in libPods.a(POPSpringAnimation.o)
      _POPPropertyAnimationState::readObjectValue(std::__1::shared_ptrPOP::Vector_, objc_object_) in libPods.a(POPSpringAnimation.o)
      _POPSpringAnimationState::hasConverged() in libPods.a(POPSpringAnimation.o)
      ...
  "std::__1::__shared_weak_count::__release_shared()", referenced from:
      std::__1::shared_ptr<POP::Vector const>::~shared_ptr() in libPods.a(POPSpringAnimation.o)
      std::__1::shared_ptrPOP::Vector::~shared_ptr() in libPods.a(POPSpringAnimation.o)
      std::__1::shared_ptr<POPAnimatorItem>::~shared_ptr() in libPods.a(POPAnimator.o)
  "std::__1::__vector_base_common<true>::__throw_length_error() const", referenced from:
      std::__1::vectorstd::__1::shared_ptr<POPAnimatorItem, std::__1::allocatorstd::__1::shared_ptr<POPAnimatorItem > >::allocate(unsigned long) in libPods.a(POPAnimator.o)
  "vtable for __cxxabiv1::__class_type_info", referenced from:
      typeinfo for _POPAnimationState in libPods.a(POPAnimation.o)
      typeinfo for std::__1::default_deletePOP::Vector in libPods.a(POPSpringAnimation.o)
      typeinfo for std::__1::default_delete<POPAnimatorItem> in libPods.a(POPAnimator.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "typeinfo for std::__1::__shared_weak_count", referenced from:
      typeinfo for std::__1::__shared_ptr_pointer<POP::Vector*, std::__1::default_delete<POP::Vector>, std::__1::allocatorPOP::Vector > in libPods.a(POPSpringAnimation.o)
      typeinfo for std::__1::__shared_ptr_pointer<POPAnimatorItem*, std::__1::default_delete<POPAnimatorItem>, std::__1::allocator<POPAnimatorItem> > in libPods.a(POPAnimator.o)
  "___cxa_begin_catch", referenced from:
      ___clang_call_terminate in libPods.a(POPAnimation.o)
  "operator new(unsigned long)", referenced from:
      -[POPAnimation _initState] in libPods.a(POPAnimation.o)
      -[POPSpringAnimation _initState] in libPods.a(POPSpringAnimation.o)
      -[POPSpringAnimation init] in libPods.a(POPSpringAnimation.o)
      std::__1::shared_ptrPOP::Vector::shared_ptr<POP::Vector, void>(POP::Vector_) in libPods.a(POPSpringAnimation.o)
      -[POPAnimator addAnimation:forObject:key:] in libPods.a(POPAnimator.o)
      std::__1::liststd::__1::shared_ptr<POPAnimatorItem, std::__1::allocatorstd::__1::shared_ptr<POPAnimatorItem > >::push_back(std::__1::shared_ptr<POPAnimatorItem> const&) in libPods.a(POPAnimator.o)
      std::__1::vectorstd::__1::shared_ptr<POPAnimatorItem, std::__1::allocatorstd::__1::shared_ptr<POPAnimatorItem > >::allocate(unsigned long) in libPods.a(POPAnimator.o)
      ...
  "std::terminate()", referenced from:
      ___clang_call_terminate in libPods.a(POPAnimation.o)
  "std::__1::__shared_weak_count::~__shared_weak_count()", referenced from:
      std::__1::__shared_ptr_pointer<POP::Vector_, std::__1::default_deletePOP::Vector, std::__1::allocatorPOP::Vector >::~__shared_ptr_pointer() in libPods.a(POPSpringAnimation.o)
      std::__1::__shared_ptr_pointer<POPAnimatorItem*, std::__1::default_delete<POPAnimatorItem>, std::__1::allocator<POPAnimatorItem> >::~__shared_ptr_pointer() in libPods.a(POPAnimator.o)
  "operator delete(void*)", referenced from:
      -[POPAnimation _initState] in libPods.a(POPAnimation.o)
      _POPAnimationState::~_POPAnimationState() in libPods.a(POPAnimation.o)
      -[POPSpringAnimation _initState] in libPods.a(POPSpringAnimation.o)
      -[POPSpringAnimation init] in libPods.a(POPSpringAnimation.o)
      -[POPSpringAnimation dealloc] in libPods.a(POPSpringAnimation.o)
      -[POPSpringAnimation setSolver:] in libPods.a(POPSpringAnimation.o)
      _POPSpringAnimationState::~_POPSpringAnimationState() in libPods.a(POPSpringAnimation.o)
      ...
  "___gxx_personality_v0", referenced from:
      __ZL13_staticStates_block_invoke in libPods.a(POPAnimatableProperty.o)
      __ZL13_staticStates_block_invoke_2 in libPods.a(POPAnimatableProperty.o)
      __ZL13_staticStates_block_invoke_3 in libPods.a(POPAnimatableProperty.o)
      __ZL13_staticStates_block_invoke_4 in libPods.a(POPAnimatableProperty.o)
      __ZL13_staticStates_block_invoke_5 in libPods.a(POPAnimatableProperty.o)
      __ZL13_staticStates_block_invoke_6 in libPods.a(POPAnimatableProperty.o)
      __ZL13_staticStates_block_invoke_7 in libPods.a(POPAnimatableProperty.o)
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by yanglinfang** [comment]
thanks! 
very helpful!

**Comment by olivermontes** [comment]
in my case:

- Problem become from "AwesomeAppTests" target from Xcode configuration
- im add "-lc++" to Other Linker Flags in your Build Settings.

Thanks @comyar
