### ISSUE TITLE
POPDecayAnimation treating NSValue/CGRect as nil

### ISSUE THREAD

**Issue by freak4pc** [facebook/pop#250]
Hey, I'm trying to animate the bounds of an object as follows 

``` 
let imgPosAnim          = POPDecayAnimation(propertyNamed: kPOPLayerBounds)
let toPoint             = NSValue(CGRect: CGRectMake(0, 64, self.view.width, self.view.width))
imgPosAnim.toValue      = toPoint
img.pop_addAnimation(imgPosAnim, forKey: "position")

log("\(toPoint)")
log(imgPosAnim.toValue)
```

This logs out `ignoring to value on decay animation <POPDecayAnimation:0x7fdc87811640; from = null; to = null; deceleration = 0.998000>`

The two logs at the end show toPoint is `NSRect: {{0, 64}, {375, 375}}` but the assigned value of toValue is `nil` for some reason. 

Pulling my hair on this. Any ideas?

Thanks :)

**Comment by freak4pc** [comment]
This workaround does the trick but I'm not sure why the aforementioned solution won't work.
Separating the creation and the property. 
```
let imgPosAnim          = POPSpringAnimation()
imgPosAnim.property     = POPAnimatableProperty.propertyWithName(kPOPViewFrame) as! POPAnimatableProperty

...
...
...
```

**Comment by grp** [comment]
For decay animations, the target is determined by the velocity input, rather than by a `toValue`, which is what the warning is about. But with a `POPSpringAnimation`, it's based on the `toValue`. If there's a specific desired destination, a spring animation is usually better.
