### ISSUE TITLE
Spring animation errors on CGPoint type

### ISSUE THREAD

**Issue by imownbey** [facebook/pop#251]
When using a CGPoint type (I have tested both kPOPViewCenter and kPOPViewScaleXY at least) I get an error: 

```
Terminating app due to uncaught exception 'Invalid value', reason: 'NSPoint: {1, 1} should be of type int'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000102c4d885 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x00000001026c2df1 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000102c4d7bd +[NSException raise:format:] + 205
	3   Bumper                              0x000000010183de3b _Z8POPUnboxP11objc_objectR12POPValueTypeRmb + 1243
	4   Bumper                              0x00000001018581e8 -[POPPropertyAnimation setToValue:] + 152
```

This is reproducible with the following code:

```
let spring = POPSpringAnimation(propertyNamed: kPOPViewScaleXY)
spring.dynamicsTension = 150
spring.dynamicsFriction = 15
spring.velocity = 0
spring.toValue = NSValue(CGPoint: CGPointMake(1, 1))
view.pop_addAnimation(spring, forKey: "springAnim")
```

**Comment by kimon** [comment]
Since you're animating a view, could you try creating and passing in an NSPoint for the to value?

**Comment by darknoon** [comment]
On 64-bit, NSPoint is the same as CGPoint. 

1. View center doesn't exist on OS X
2. Scale XY is a CGSize not a CGPoint, right? Not sure if that makes a difference.

**Comment by imownbey** [comment]
Oh sorry I typod. Let me confirm that I didn't also do that typo in my code.

**Comment by imownbey** [comment]
this is on iOS by the way. It also does not work with CGSize:

```
2015-07-02 17:23:24.487 Bumper[35557:7825844] *** Terminating app due to uncaught exception 'Invalid value', reason: 'NSSize: {1, 1} should be of type int'
```

**Comment by imownbey** [comment]
Notice the error says specifically that the type should be int

**Comment by Kirow** [comment]
I have same error.

**Comment by grp** [comment]
@Kirow, make sure that the property you're using needs the same type that you are passing in.

(The issue with the initial example is that `0` for `velocity` isn't the right type for the scale property.)
