### ISSUE TITLE
Static library copy headers build phase is incorrect

### ISSUE THREAD

**Issue by JonasGessner** [facebook/pop#253]
The static library target has a "Copy Headers" build phase. This won't work when archiving and the docs for creating a static library explicitly advise against using a "Copy Headers" build phase in a static library (it is meant for frameworks). A "Copy Files" build phase should be used instead.

https://developer.apple.com/library/ios/technotes/iOSStaticLibraries/Articles/creating.html

"If your library target has a “Copy Headers” build phase, you should delete it; copy headers build phases do not work correctly with static library targets when performing the “Archive” action in Xcode."

It is a very easy fix and archiving will work once the "Copy Files" build phase is used.

I have opened the same ticket on AsyncDisplayKit too: https://github.com/facebook/AsyncDisplayKit/issues/546#issuecomment-119714449

**Comment by grp** [comment]
We don't suggest using the Xcode project for anything more than testing or examples. It's an non-human-readable format and is hard to make sure it's correct. Cocoapods has a human-readable format and also knows how to correctly set up dependencies as appropriate for your project — it's definitely the easiest way to use Pop.

I'd take a pull request, but I don't think we're going to proactively update the Xcode project to support this better.
