### ISSUE TITLE
Can’t build OS X project using pop-osx.framework (Swift)

### ISSUE THREAD

**Issue by jbrennan** [facebook/pop#255]
Hey all,

I’m trying to use pop in a Swift OS X project (Yosemite). Here’s what I’ve got:

1. Start with the standard Cocoa OS X project template
2. Add pop as a git submodule
3. Add the pop.xcodeproj file to my Mac app project
4. In my app’s Target’s General tab, I’ve added pop as an embedded framework (I know it’s hard to tell which is iOS and which is OS X from that dialog, but it shows up on the General tab as being in ../build/debug or whatever, not iphoneos, so I’m inferring this means I’ve chosen the right one
5. Try to `import pop` in my ViewController.swift.

I get the following error

```
/Users/jason/cocoa/TestPop/TestPop/ViewController.swift:10:8: error: no such module ‘pop’
```

From my build log, it looks like pop is building just fine. Any suggestions?

**Comment by grp** [comment]
We only really support using Cocoapods for Pop, since it's so hard to maintain compatible Xcode projects for it. Could you try using that instead?

**Comment by grp** [comment]
Also, did you import Pop in your bridging header? You'll need that in order to use it.

**Comment by jbrennan** [comment]
Interesting. OK, yes, I had to:

1. Make a bridging header, `#import <pop/POP.h>`
2. Add `pop, recursive` to my target’s `Header Search Paths`.

Then it worked. Of course, this was just a test *app*, the next step is getting this working in my own *framework*, which seems to not like bridging headers.

Thanks for your help!
