### ISSUE TITLE
Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by MithunReddy** [facebook/pop#260]
Just downloaded source compiled and added framework to project. 

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_POPDecayAnimation", referenced from:
      objc-class-ref in BSThreadThreadViewController.o
  "_OBJC_CLASS_$_POPSpringAnimation", referenced from:
      objc-class-ref in BSThreadThreadViewController.o
  "_kPOPLayerPositionX", referenced from:
      -[BSThreadThreadViewController viewDidLoad] in BSThreadThreadViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by grp** [comment]
Hi, we suggest using Cocoapods for installing Pop, since it can handle all of the setup for you. In this case, though, you'll probably need to add Pop to your list of libraries to link.
