### ISSUE TITLE
pop doesn't support swift?

### ISSUE THREAD

**Issue by Heisenbean** [facebook/pop#261]
I'm trying use pop in a project with swift,so i create a bridge file,and include ```<POP/POP.h>```
then i import POP in ```ViewController.swift```.
I get "```no such module 'POP'```" error when i build it.

![image](https://cloud.githubusercontent.com/assets/7660120/8899252/73884d8c-3464-11e5-9655-d8f5d0768090.png)

![image](https://cloud.githubusercontent.com/assets/7660120/8899257/84858186-3464-11e5-9d48-f1a4936a574c.png)

**Comment by grp** [comment]
Pop should work with Swift. You might need to import 'pop' in lowercase? If that doesn't work, there's a few projects on GitHub using Pop with Swift and you could take a look how they're doing it.
