### ISSUE TITLE
fabsf() used with CGFloat triggers warnings

### ISSUE THREAD

**Issue by K-cat** [facebook/pop#262]
<img width="287" alt="2015-07-29 5 58 23" src="https://cloud.githubusercontent.com/assets/7700379/8955107/9b30b950-361c-11e5-8dcb-9b631249e98f.png">
Please fix them!I use cocoapods,so I don't wanna unlock source files,thank you

**Comment by wlodarcm** [comment]
Yes, please solve this issue.

**Comment by marcferna** [comment]
+1

**Comment by BigHub** [comment]
+1

**Comment by Jaymassena** [comment]
Would be great to clear up my only build warnings :+1:

**Comment by grp** [comment]
This should be an easy pull request for any new contributors!

**Comment by grp** [comment]
Talked to @kimon and turns out this is fixed on master. You can wait for the next release, or track HEAD directly.
