### ISSUE TITLE
Update Podspec to support 0.38.2

### ISSUE THREAD

**Issue by iantheparker** [facebook/pop#264]
Here's the issue from Cocoapods' perspective 
`user_target_xcconfig` doesn't merge build settings which accept multiple values -
https://github.com/CocoaPods/CocoaPods/issues/3813#issuecomment-127218342

**Comment by suhinini** [comment]
Yep +1

**Comment by AEugene** [comment]
Same issue

**Comment by TiagoVeloso** [comment]
Same here

**Comment by mmilosevic** [comment]
Same here

**Comment by Mazyod** [comment]
:hand:
