### ISSUE TITLE
Sucks. How to add it to my project manually?

### ISSUE THREAD

**Issue by lennondong** [facebook/pop#268]
It's hard to add it to my project .It's not easy at all!!!!!!

**Comment by Bintong** [comment]
Pop is available on CocoaPods. Just add the following to your project Podfile:
pod 'pop', :git => 'https://github.com/facebook/pop.git'

if you do not know what is cocoaPods . https://cocoapods.org/     see detail

**Comment by lennondong** [comment]
Thanks for your reply.  I know how to add it by pods. But I need to add it manually for the project.

**Comment by grp** [comment]
We suggest Cocoapods for using Pop, but you can also use it as a framework subproject or through Carthage. I agree Pop is hard to install by manually copying source files, but generally that's not a great idea because it ends up being hard to update later on.

**Comment by lennondong** [comment]
@grp @Bintong OK.I'm using Cocoapods and install pop successfully.
