### ISSUE TITLE
Implicit declaration of function 'POPLayerSetRotationY' is invalid in C99

### ISSUE THREAD

**Issue by y0unghe** [facebook/pop#271]
`POPLayerSetRotationY(self.frontView.layer, POPDegreesToRadians(progress));
`
outputs error: 
`Implicit declaration of function 'POPLayerSetRotationY' is invalid in C99`

**Comment by grp** [comment]
Will need more information to look into this — are you importing the header defining that function? (I'm assuming this is in your code, not Pop itself.)
