### ISSUE TITLE
kPOPLayerScaleXY - Bug.  why the code was sometimes rotated 180° automatically？

### ISSUE THREAD

**Issue by yexiahua** [facebook/pop#273]
my code

show:
POPSpringAnimation *springAnimation = [POPSpringAnimation animationWithPropertyNamed:kPOPLayerScaleXY];
    springAnimation.fromValue = [NSValue valueWithCGSize:CGSizeMake(0.1f, 0.1f)];
    springAnimation.toValue = [NSValue valueWithCGSize:CGSizeMake(1.0f, 1.0f)];
    springAnimation.springSpeed = 10.0;
    springAnimation.springBounciness = 10.0f;
    [_optionBgSC.layer pop_addAnimation:springAnimation forKey:@"scaleAnimation"];

hide:
POPSpringAnimation *springAnimation = [POPSpringAnimation animationWithPropertyNamed:kPOPLayerScaleXY];
    springAnimation.fromValue = [NSValue valueWithCGSize:CGSizeMake(1.0f, 1.0f)];
    springAnimation.toValue = [NSValue valueWithCGSize:CGSizeMake(0.0f, 0.0f)];
    springAnimation.springSpeed = 10.0;
    springAnimation.springBounciness = 10.0f;
    [_optionBgSC.layer pop_addAnimation:springAnimation forKey:@"scaleAnimation"];

**Comment by darknoon** [comment]
Could you attach a video? Nothing is wrong on a cursory inspection.

**Comment by yexiahua** [comment]
on ios8 test.   thank you 
![xjk7_ g5 c6 _lksx q01 9](https://cloud.githubusercontent.com/assets/7960273/9866667/cd51b286-5b97-11e5-9750-7a6e76a659e1.gif)

**Comment by yangyang12138** [comment]
I also met.

**Comment by grp** [comment]
The issue is that the scale goes below zero, so it flips vertically. You'll want to use the `clampMode` property to clamp it to the end value when scaling down.

**Comment by warpling** [comment]
:+1:
