### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_OBJC_CLASS_$_CIColor", referenced from:       objc-class-ref in POPCGUtils.o ld: symbol(s) not found for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by jason469618528** [facebook/pop#283]
xcode7 ios9 ,没有使用cocopods ，当我删除我项目中的paypal支付SDK引用后，就报这个错。加上就又好了?

**Comment by grp** [comment]
Hi, I can't read your issue message, but it looks like you might need to add `CoreImage` to your `Link Binary with Libraries` build phase.

**Comment by jason469618528** [comment]
not cocopods,   i add coreimage to Link Binary with Libraries,Or wrong!

**Comment by jason469618528** [comment]
OK,thanks @grp

**Comment by jamesgpearce** [comment]
Shortening title; used to also say: 'referenced from: objc-class-ref in POPCGUtils.o ld: symbol(s) not found for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation)'
