### ISSUE TITLE
Animate New added NSLayoutConstraint

### ISSUE THREAD

**Issue by hashemp206** [facebook/pop#284]
Is this possible to animate presence of a new layout constraint?
```objective-c
[self.nameLabelEdgeConstraint autoRemove];
 self.nameLabelVerticalAxisConstarint = [self.nameLabel autoAlignAxis:ALAxisVertical toSameAxisOfView:self.containerView];
```
I can animate this change using UIView block based animation and calling ```layoutIfNeeded``` in the block. is this possible to do this with POP?

**Comment by grp** [comment]
I'd suggest adding the new constraint with a value of zero, then using Pop to animate the constraint's value to the target. Pop doesn't support implicit animation blocks, since there's be no good way to configure the velocity and other dynamics properties for it.

**Comment by hashemp206** [comment]
thanks. I always wanted to know why pop doesn't support animation blocks and you tick the trick!
