### ISSUE TITLE
Non-modular header troubles

### ISSUE THREAD

**Issue by Leshich** [facebook/pop#285]
I have a problem after installing new Xcode 7.1 from Mac App Store. I have searched for a solution [here](http://stackoverflow.com/questions/24103169/swift-compiler-error-non-modular-header-inside-framework-module). Nothing worked. So can you help me to find a way why this happened.

I use a pop framework with cocoapods, maybe it's not a pop problem, but I really want to know what's happened. Everything I animate in the project depends on pop framework.

Here is a screenshot of errors:
![screen shot 2015-10-22 at 18 29 30](https://cloud.githubusercontent.com/assets/4246455/10666405/dd76468e-78ea-11e5-8dd0-76adbf09dc74.png)

Sorry for such a stupid issue, but I really tried to solve it by myself.

**Comment by Leshich** [comment]
So nice. I found a solution 5 mins after publishing here.

https://github.com/CocoaPods/CocoaPods/issues/4056
• If you get an error stating "Include of non-modular header inside framework module" for a 
framework that previously compiled, make sure the "Always Search User Paths" 
build setting is set to "No". The default is "Yes" only for legacy reasons. (22784786)

**Comment by zeronoun** [comment]
Something happened between Xcode 7.1 Beta 3 (Build 7B85) and final release (Build 7B91b).

**Comment by grp** [comment]
I'd make sure you either have modules disabled or enabled consistently. For example, if pop has them disabled, disable them in the main project too.

The best way to debug these issues is to look at the actual `clang` invocations Xcode is running, so I'd take a look at the build log too.

**Comment by blangslet** [comment]
Getting similar errors with Pop on xcode 7.1 (7B91b). Any advice?
```Include of non-modular header inside framework module 'pop.POP'```

**Comment by Leshich** [comment]
https://github.com/CocoaPods/CocoaPods/issues/4420 a workaround here. I would suggest that we have to wait for cocoapods update.

```
post_install do |installer|
    `find Pods -regex 'Pods/pop.*\\.h' -print0 | xargs -0 sed -i '' 's/\\(<\\)pop\\/\\(.*\\)\\(>\\)/\\"\\2\\"/'`
end
```

**Comment by blangslet** [comment]
@Leshich YASSSSS!!! Thank you kind sir!!! 🎉🔥🔥🔥
