### ISSUE TITLE
TVOS / SceneKit

### ISSUE THREAD

**Issue by HUGEwindow** [facebook/pop#290]
Is it possible to use kPOPSCNNodeScale on TVOS? 
I am having trouble implementing any node based animations 

Thanks in advance

**Comment by grp** [comment]
If you can set the property manually, Pop should be able to animate it. What specific error or issues are you seeing here?

**Comment by HUGEwindow** [comment]
I got it to work, I needed to uncomment SceneKit conditionals

**Comment by robinmacharg** [comment]
For SceneKit/Pop Googlers arriving directly here: As stated in [the docs](https://github.com/facebook/pop#scenekit) - instead of uncommenting conditionals - you can add a preprocessor macro to enable SceneKit animations: `POP_USE_SCENEKIT=1`
