### ISSUE TITLE
Support building as a module for OS X

### ISSUE THREAD

**Issue by toulouse** [facebook/pop#291]
Currently, it's not enabled for OS X, and the modulemap for iOS doesn't work when used for OS X, presumably because the header search paths are different somehow.

(Context: I was trying to add it as an embedded framework on OS X without modification, with little luck.)

**Comment by grp** [comment]
In general we suggest using CocoaPods for Pop. The Xcode projects are maintained by the community so while we'd be happy to accept a pull request to change it, it's probably not something that at least I know about setting up myself.
