### ISSUE TITLE
Work with Swift 2.1?

### ISSUE THREAD

**Issue by l800891** [facebook/pop#292]
Having trouble using pop with objc- bridge.. Is there any sample project or documentation I can refer?
Thanks!

**Comment by grp** [comment]
It's hard to say without a specific error message or issue you're hitting, but you might look at the past resolved issues related to Swift: https://github.com/facebook/pop/issues?utf8=✓&q=swift

**Comment by vinbhai4u** [comment]
I have created a sample swift project 

https://github.com/vinbhai4u/pop-swift-sample

hope it helps
