### ISSUE TITLE
Pods update for new release

### ISSUE THREAD

**Issue by mariohahn** [facebook/pop#299]
You haven't updated the latest version to cocoapods.

https://github.com/CocoaPods/Specs/tree/master/Specs/pop

**Comment by hfossli** [comment]
As a long as 1.0.9 is tagged in this repo is there any reason for it not being published to trunk of cocoapods? I would highly appreciate if you could publish the 1.0.9 podspec :)

**Comment by grp** [comment]
Sorry about that, missed this issue. Pushed now.

**Comment by hfossli** [comment]
Thank you 🌈
