### ISSUE TITLE
where is the framework biniary location after build/archive?

### ISSUE THREAD

**Issue by liuxuan30** [facebook/pop#300]
Maybe this is a newbee question, but I want to ask is, I just want to use the framework binary and embed it into my library; I don't want to drag the whole project into my project, I think it will cause the build processing slow.
So I download pop and tried to run it and archive it, but I cannot find it. Thanks for help!

**Comment by grp** [comment]
It's probably in your DerivedData folder. Unfortunately the specific path depends on where you checked out Pop on your computer, but if you look under ~/Library/Developer/Xcode/DerivedData/pop-<random characters>/Build/Products`, it's probably under there somewhere.

Let me know if you still can't find it! You can always use CocoaPods (or Carthage) for automatic integration as well.

**Comment by liuxuan30** [comment]
Thanks @grp, I managed to find one under:~/Library/Developer/Xcode/DerivedData/pop-dqzimrpnehznkqcunznjnierhcqm/Build/Products/Debug-iphonesimulator/, which presents me a pop.framework with size 238B. 

This brings me 2 questions:
1. From the path, it seems like a debug build(Debug-iphonesimulator), but I cannot find a release(archived) one in other levels of directories. Where is the archived one?

2. It smells I should use debug build for running, and release build for app store submission, using source code project can help erase the build setting options. But could pods or Carthage solve the debug<->release problem?
