### ISSUE TITLE
Universal framework target?

### ISSUE THREAD

**Issue by rbarbish** [facebook/pop#312]
Hey, I had to follow this tutorial to create a framework that would run on both the iOS simulator and an iOS device - https://medium.com/@syshen/create-an-ios-universal-framework-148eb130a46c#.uxvt70svh

I don't have a ton of experience with this universal frameworks, I just starting running into the error "ignoring file ../pop.framework/pop, missing required architecture x86_64 in file .../pop.framework/pop (2 slices)" when attempting to run my app on the simulator and creating a universal framework seemed to be the solution.

Can someone experienced with this issue please either 1. Add details in the .ReadMe how to create a framework that will run just fine on iOS Simulator + iOS Devices as an Embedded Binary or 2. Propose another solution due to my ignorance on the issue. 

If this is a valid issue I would love to see a shared universal target added to the project that combines the iphonesimulator and iphoneos frameworks into a single file.

Thanks, Ross

**Comment by grp** [comment]
Hi! We suggest using CocoaPods to install Pop, since the build configuration is standardized with that approach. If you're doing something custom, it's unlikely we can help with your specific issue, but Pop should be no different from any other set of code in what you'd need to do.
