### ISSUE TITLE
Facebook-pop animation paused when UITableView scrolling

### ISSUE THREAD

**Issue by IvanChan** [facebook/pop#322]
Facebook pop is NOT friendly with a scrolling tableview? My Facebook-pop animation paused when UITableView scrolling.

A pop animation will pause when tableView is scrolling, I thought the problem is the runloop mode for the displayLink? but the source code seems the the displayLink already added to common modes?

Any one ran into similar circumstance ?
How to fix that? (I don't want to change the source code only for my project use in case leading to some other bugs)

**Comment by kimon** [comment]
Report appreciated. If you could, please attach a sample app that
demonstrates the issue - it will help speedup, the investigation.

**Comment by IvanChan** [comment]
I just present my animation in main thread normally,  @kimon you means that I should call pop_addAnimation in None-main thread?

I try API below to change modes, and it doesn't work.

- (void)performSelector:(SEL)aSelector withObject:(nullable id)anArgument afterDelay:(NSTimeInterval)delay inModes:(NSArray<NSString *> *)modes;

**Comment by IvanChan** [comment]
Sorry for my stupid logic code. I just keep calling this method to add a animation.
