### ISSUE TITLE
How can I get the pop.framework quickly on iOS platform?

### ISSUE THREAD

**Issue by dustturtle** [facebook/pop#323]
I've used pop via cocoapods easily. Now I am wondering how to use this without pods. Anyone can help? Thanks

**Comment by dustturtle** [comment]
dyld: Library not loaded: @rpath/pop.framework/pop
  Referenced from: /var/containers/Bundle/Application/327F32FF-87C2-4049-B304-0F070BD8E399/testStretch.app/testStretch
  Reason: image not found

**Comment by dustturtle** [comment]
solved.

**Comment by dustturtle** [comment]
embedded dylibs/frameworks are only supported on iOS 8.0 and later (@rpath/pop.framework/pop) for architecture arm64  ??? how to work on iOS7 via framework? or impossible?

**Comment by grp** [comment]
Pop is no different from any other library in this respect, so I'd point you to the Apple developer documentation on where dynamic frameworks are supported. Note that CocoaPods is recommended for Pop since it simplifies the installation process significantly.

**Comment by dustturtle** [comment]
I know the dynamic framework can not be used before iOS8. There still have a type of "fake framework" was used before iOS8.
But pop have the problem of header files always tell us like this   'pop/POP.h' file not found
If you use the .a or just add the pop folder in your project, the problem is always there. Some people changed lots of .h files to make the project work. But I still believe that facebook should give us an elegant solution.

**Comment by dustturtle** [comment]
@grp  I don't think this problem don't make sense. Many developers faced the same problem like me. Manual integration is suck for pop.

**Comment by grp** [comment]
It's hard to make an Xcode project that automatically configures a static library, hence CocoaPods to solve that automatically. You can of course always configure the header search paths manually to use Pop as a static library without it, but it's nontrivial enough that it's hard to claim support for that.

**Comment by dustturtle** [comment]
The main problems are the header files. 
Look the macro below:
#if __has_include(<TestHead/TestHead.h>)
#import <TestHead/TestHead.h>
#else
#import "TestHead.h"
#endif 
Maybe this will be helpful. Thanks.

**Comment by dustturtle** [comment]
```
#if __has_include(<TestHead/TestHead.h>)
#import <TestHead/TestHead.h>
#else
#import "TestHead.h"
#endif 
```

**Comment by dustturtle** [comment]
@grp

**Comment by jungchris** [comment]
3 years later someone that doesn't use CocoaPods was experiencing the same issue. If I find a work-around I'll post another message here.
