### ISSUE TITLE
READ ME in Swift

### ISSUE THREAD

**Issue by brightfuture** [facebook/pop#324]
It'd be a lot easier for those who learned Swift from the beginning of iOS development to understand the usage.

**Comment by nlutsenko** [comment]
Sounds indeed useful. Marking as enhancement and looking forward to see a Pull Request!

**Comment by nemesis** [comment]
@brightfuture You'll be able to find a few examples of usage [here](https://github.com/hossamghareeb/Facebook-POP-Tutorial/tree/master/Swift%20Version) (not Swift 3.0 though)

**Comment by Adriana1999** [comment]
German
