### ISSUE TITLE
Cannot install pod

### ISSUE THREAD

**Issue by zargaryan** [facebook/pop#325]
pod "EmailTemplates" tried everything on this topic nothing helps.
The output is :

Analyzing dependencies
[!] Unable to find a specification for `EmailTemplates`

Podfile is:

#use_frameworks!

target "TargetName" do
    pod 'GoogleIDFASupport'
    pod 'Mixpanel'
    pod 'RMUniversalAlert'
    pod 'FMDB'
    pod 'LaunchKit'
    pod 'LGSideMenuController', '~> 1.0.0'
    pod 'QBImagePickerController'
    pod 'Realm'
    pod 'EmailTemplates'
end

**Comment by grp** [comment]
This is the issue page for Pop, an animation library. Please re-open if your issue is related to Pop — I didn't see it mentioned in your message.
