### ISSUE TITLE
iOS10 behavior: isPrefetchingEnabled causes issues with scaling. 

### ISSUE THREAD

**Issue by kjsujesh** [facebook/pop#329]
The iOS10 UICollectionView property of isPrefetchingEnabled is causing the cells to be not scaled correctly. 
For example, the cells which are not dequeued to be updated are showing up incorrectly scaled.

**Comment by grp** [comment]
Do you have a sample project that shows this issue? An issue like this would likely depend on what properties are being modified and when the animations are added and removed. In general, if changing the property manually works, animating it with Pop should work too. It might be worth checking that the Pop animation is only running at times when changing the property manually is supported.
