### ISSUE TITLE
Please update to Swift 3.0 Xcode 8! :)

### ISSUE THREAD

**Issue by nhantrivinh** [facebook/pop#335]

**Comment by grp** [comment]
Pop is written in Objective-C(++), not Swift, so it should be importable by any version of Swift. Are you seeing an error trying to use it from Swift 3?

**Comment by brightfuture** [comment]
Want to see a Swift version 🤗

**Comment by mradzinski** [comment]
@brightfuture Is having a Swift version going to make Pop better in any way? Pop is compatible with every Swift version available, so I'm not getting your point...

**Comment by everSin** [comment]
When will it support Swift Package Manager? 
Thanks in advance!

**Comment by brightfuture** [comment]
@mradzinski having a Swift version will make folks only learned Swift understand how Pop works a lot easier.
