### ISSUE TITLE
How do I reset layer rotation?

### ISSUE THREAD

**Issue by sryze** [facebook/pop#337]
I created a rotation animation like this:

```objective-c
POPBasicAnimation *a = [POPBasicAnimation animationWithPropertyNamed:kPOPLayerRotation];
a.fromValue = @0;
a.toValue = @(DEGREES_TO_RADIANS(-38));
a.beginTime = CAMediaCurrentTime();
a.duration = 1;
[view.layer pop_addAnimation:a forKey:nil];
```

However, the next time the view appears it's already rotated. How do I reset the rotation back to 0?

I've already tried setting `transform` and `affineTransform` to the identity transform but that didn't work for some reason.

**Comment by grp** [comment]
Pop changes object properties over time. You can of course change those properties manually when Pop isn't animating them, before adding an animation or after it is finished or removed.

Assuming your `propertyName` is in this case `kPOPLayerRotation`, that will change `view.layer.transform`. Remove the animation and set it back to the default value, `CATransform3DIdentity`, to reset.

If the view is still appearing rotated, there are two possibilities. First, you may not be actually setting the property as you expect — maybe the `view` is unexpectedly `nil` at that point? Or, something might set the property back, either from an ongoing Pop animation or from your own code.

**Comment by sryze** [comment]
You were right, it was a bug in my code. Thanks anyway!

**Comment by sryze** [comment]
Apparently I haven't fixed it as it's still not working. 

I don't know what I'm doing wrong, I'm resetting the `transform` both inside the completion block and before the animation begins but the view is somehow rotated.

**Comment by sryze** [comment]
This seems to occur only if I cancel the animation before it begins (but is already added). If it's  cancelled while executing or after completion everything works great...

**Comment by grp** [comment]
I would suggest logging the transform when the view is appearing incorrectly. If the transform is non-identity at that point, it isn't being set correctly.

If it is identity, something else must be setting it back afterwards. To debug that, you could add a breakpoint on `-[CALayer setTransform:]`.

**Comment by sryze** [comment]
When the animation is added to the layer the `transform` is identity. However, when inspecting the view in the view hierarchy debugger it's stretched out:

![screen shot 2016-10-02 at 14 41 22](https://cloud.githubusercontent.com/assets/4525736/19019578/a2994226-88ae-11e6-94f9-19f2d5e107d4.png)

At that point `transform` is equal to:

```
(m11 = 0.78801065683364868, 
m12 = -0.6156613826751709, 
m13 = 0,
m14 = 0,
m21 = 0.6156613826751709, 
m22 = 0.78801065683364868, 
m23 = 0, 
m24 = 0, 
m31 = 0, 
m32 = 0, 
m33 = 1, 
m34 = 0, 
m41 = 0, 
m42 = 0, 
m43 = 0, 
m44 = 1)
```

This is how it normally looks (unrotated):

![screen shot 2016-10-02 at 14 42 38](https://cloud.githubusercontent.com/assets/4525736/19019582/ae8bfc68-88ae-11e6-8ae5-912b3274aa80.png)

And this is how it should look when rotated:

![screen shot 2016-10-02 at 14 45 21](https://cloud.githubusercontent.com/assets/4525736/19019593/fcdbc43e-88ae-11e6-9bd2-43abba8785df.png)

I'm not an expert in transform math but to me appears to be rotated along the Y axis on the first (bugged) image. Any ideas why it might be? This is the only animation that changes its angle.

**Comment by grp** [comment]
Is that a different issue from your first one? I'm not sure how to match those screenshots up with what you said initially.

**Comment by grp** [comment]
In the first screenshot, I think the issue is that you are setting the `frame` on the layer, which *includes* the `transform`. You can see how this causes the layer bounds to be squished in order to fit into the `frame` you set. Try setting the `bounds` and `center` directly rather than the `frame` when using a custom `transform`.

**Comment by sryze** [comment]
I'll try that, thanks.
