### ISSUE TITLE
Is there a way to translate a view?

### ISSUE THREAD

**Issue by supratik94** [facebook/pop#339]
The layers can be transtated easily using **kPOPLayerTranslationY**. Is there a way to do in on a view for the same? Mostly, applicable to subViews in **UIViews**

**Comment by grp** [comment]
Each `UIView` has an associated `CALayer`, accessible through the property `layer`. You can animate that backing layer and it will apply to the view as well.

If you just want to move the view rather than adjust the `transform`'s translation, you can also use `kPOPViewCenter`.
