### ISSUE TITLE
How to  implement the function like CAReplicatorLayer class?

### ISSUE THREAD

**Issue by sunjmmeishao** [facebook/pop#345]
does pop support the function?

**Comment by grp** [comment]
I'm not sure what function you mean — `CAReplicatorLayer` is meant for display, but Pop controls animation. Using custom properties, you could animate the properties of a `CAReplicatorLayer`, but I don't believe there are any built in properties designed for it.

**Comment by sunjmmeishao** [comment]
@grp 
hi，
my meaning is the performance of POP. look like that the performance is just in relation to UIView or CALayer or iOS.   I wonder if POP's performance is just better a little than coreAnimation. 
I have  another question. How  does POP  support a path. POP is not  expose the time parameter。I can not calculate the position of a view for my own use. 
thanks the source code, I can study very much！

**Comment by grp** [comment]
Pop can't compare to `CAReplicatorLayer`; it performs a different function. Compared to `CAAnimation`, Pop is generally slower: it has to update the property each frame. However, Pop is more flexible, for example for changing animations dynamically based on user interaction.

Pop doesn't support animating paths. If you just need the progress of an animation, you can use a custom `POPAnimatableProperty` with a property representing animation progress.
