### ISSUE TITLE
Parameter 'The' not found in the function declaration

### ISSUE THREAD

**Issue by zeusent** [facebook/pop#363]
This is not a big problem but a problem nevertheless. As you can see in the screenshot bellow, Xcode 8.3.2 is throwing a warning when compiling the latest version of pop. It would be really nice if this could be fixed so that the warning goes away. This happens in **POPAnimation.h**.

<img width="725" alt="screen shot 2017-05-08 at 17 20 57" src="https://cloud.githubusercontent.com/assets/777591/25808522/02bc4d46-3413-11e7-97dd-7737183043e1.png">

**Comment by albinekcom** [comment]
It is already fixed (check this commit: https://github.com/facebook/pop/commit/92b2c5b7bcad64f7507da34f921492c71ff1d330) but `pop.podspec` needs to be also updated. (Probably you use this library via `CocoaPods`.)

**Comment by zeusent** [comment]
Wow! 9 months ago? Why isnt the Podspec up to date then? :(

**Comment by albinekcom** [comment]
¯\_(ツ)_/¯
I think that the best solution so far is to change into this line in your `Podfile` file:

**Comment by zeusent** [comment]
Unfortunately I am using it as a dependency of another Pod :(

**Comment by tirrorex** [comment]
@albinekcom the best solution is for the maintainer of the repo to update the pod spec...
@b3ll could we have an update please?

**Comment by b3ll** [comment]
Oops, sorry I thought I bumped the pod spec, but I accidentally forgot to actually commit the spec bumping part. I'll fix that right now

**Comment by b3ll** [comment]
Fixed! 94652b53577163c65a2b24e98ee83bbd1b6e638c

**Comment by tirrorex** [comment]
Thanks mate !

**Comment by zeusent** [comment]
Somehow I still get the 1.0.9 version :|

**Comment by b3ll** [comment]
oh I'm sorry, I forgot to update the repo (I'm still new to maintaining pods 😅). Will do so now

**Comment by b3ll** [comment]
All done!

**Comment by ChaosPredictor** [comment]
Got something similar on Xcode 9 beta6, is it the same?

<img width="968" alt="screen shot 2017-09-18 at 22 01 11" src="https://user-images.githubusercontent.com/1302083/30559368-187fb434-9cbd-11e7-8a8e-458b71e881e6.png">

pod 'pop', git: 'https://github.com/facebook/pop.git' 
Did work for me ):

**Comment by ChaosPredictor** [comment]
Got something similar on Xcode 9 beta6, pod 1.3.1. Is it the same?

<img width="968" alt="sceen" src="https://user-images.githubusercontent.com/1302083/30637897-681417ec-9e02-11e7-85d4-b9e01d913820.png">

pod 'pop', git: 'https://github.com/facebook/pop.git'
Did NOT work for me ):
