### ISSUE TITLE
Why not kPOPLayerRotationZ this enumeration? I want to rotate the animation around the Z axis.

### ISSUE THREAD

**Issue by Jinxiansen** [facebook/pop#397]
![1](https://user-images.githubusercontent.com/16829428/34428249-d150407e-ec85-11e7-8577-7d227d980906.png)

I only found kPOPLayerRotationX and kPOPLayerRotationY but no kPOPLayerRotationZ.

> English is not my native language; please excuse typing errors.

**Comment by FUWUiOS** [comment]
This is a good note

**Comment by Jinxiansen** [comment]
I use the following code to meet the demand:

```

    POPBasicAnimation * basic = [POPBasicAnimation animationWithPropertyNamed:kPOPLayerRotation];
    basic.toValue = [NSNumber numberWithFloat: M_PI * 2.0];
    basic.duration = 2;
    basic.repeatForever = YES;
    basic.timingFunction = [CAMediaTimingFunction functionWithName:kCAMediaTimingFunctionLinear];
    basic.removedOnCompletion = NO;
    [self pop_addAnimation:basic forKey:@"refreshRotationKey"];


```


However, there is a doubt, view can not be added to the navigationBar, otherwise it will lead to animation deformation.
