### ISSUE TITLE
CocoaPods update

### ISSUE THREAD

**Issue by Kaspik** [facebook/pop#413]
Hey guys! Thanks for this library.

We are using CocoaPods version (1.0.10) that is kind of outdated against current master. It's throwing warning etc against new XCode and we would love to keep using CocoaPods version instead of master.

Are you able to polish current master and release new version on CocoaPods?

Thanks!

**Comment by sirdharma** [comment]
👍 

Latest `pop` release is currently throwing warnings against latest iOS SDK, while `master` isn't. A new release would be much appreciated. Thank you for your work!

**Comment by Kaspik** [comment]
@b3ll @nlutsenko ? Any update on this? CocoaPods are far far away from current master.

**Comment by b3ll** [comment]
Sorry about this! I can update this!

**Comment by b3ll** [comment]
And updated to version 1.0.12 :)

**Comment by Kaspik** [comment]
Thank you!
