### ISSUE TITLE
Spring animation not working anymore following iOS 13 update

### ISSUE THREAD

**Issue by babkouew** [facebook/pop#424]
Hi, POPSpringAnimation is not working anymore under iOS13, the imageView appears but there is no animation anymore. Could you please check what's going on? Thanks

**Comment by pengkun** [comment]
same problem

**Comment by easoncodes** [comment]
same problem
```
[POPBasicAnimation animationWithPropertyNamed:kPOPViewFrame];
```

**Comment by zhangxu7** [comment]
same problem

**Comment by pengkun** [comment]
> 同样的问题
> 
> ```
> [POPBasicAnimation animationWithPropertyNamed:kPOPViewFrame];
> ```

我发现直接将pop源码拉进项目里使用不会崩溃

**Comment by Dr-Bootman** [comment]
that's a conflict with autolayout probably
try to set:
translatesAutoresizingMaskIntoConstraints = YES for view you are animating

**Comment by babkouew** [comment]
You, my good Sir, just solved our issue and have my gratitude.
