### ISSUE TITLE
Single frame flashes of 'initial' animation before `fromValue` kicks in.

### ISSUE THREAD

**Issue by zdavison** [facebook/pop#61]
https://github.com/zdavison/POPBug/tree/master

I've isolated a demonstrable version of this code here, with a short (shaky) vine you can view to see the bug. A few things I've noted:
- The 'add' animation is the only time this occurs. This leads me to believe it may be because we're adding a new layer and immediately animating it. I have also seen this with existing layers though.
- I've seen this behaviour with both scaling from 0, using transforms, and while animating bounds properties from CGRectZero. 
- It's intermittent, you may need to try playing with it to catch it. It also seems to only happen on my device, rather than the simulator. (Have tried on several iPads, mini, air, etc)

This could also be my own bad usage / misunderstanding, which would be great!

**Comment by walteryaron** [comment]
same here , when using POPBasicAnimation and fromValue , but with multiple times
https://www.dropbox.com/s/70540el22om3ys4/Untitled%203.m4v?dl=0
first time the frame is okay , the second time the frame get bigger then excepted

**Comment by kimon** [comment]
Sounds easy to hit. Do you mind attaching the simplest of sample apps? That will help speed up the investigation

**Comment by vburojevic** [comment]
I've noticed this issue again when using POP in custom controller transition.
Like @kimon said, temporary workaround is to set initial value of the frame.

Can you please take a look at this again?
Frame sometimes flashes before animation starts.

**Comment by patr1ck** [comment]
I'm seeing the same issue as @waltflanagan, specifically a POPSpringAnimation being applied to a layer position during an animated transition. I'll see if I can whip up a sample app. (👋)

**Comment by grp** [comment]
I would still suggest trying to set the values manually without Pop. If you still issue the issue just setting the property manually, there's not a lot Pop can do to get around that.

**Comment by swimminsurfer256** [comment]
This seems to still be an issue. A really, really hacky solution I've found is to add the subview after a delay of .01 seconds. Seems to bypass the flash.

**Comment by xquezme** [comment]
Quick fix:
```
layer.transform = CATransform3DMakeScale(0.001f, 0.001f, 1.f)
animation.fromValue = [NSValue valueWithCGSize:CGSizeMake(0.f, 0.f)];
[layer pop_addAnimation:animation forKey:@"scaleXY"];
```

**Comment by charlesvinette** [comment]
@xquezme worked like a charm and fixed the stutter, thanks!
