### ISSUE TITLE
NSCopying

### ISSUE THREAD

**Issue by KevinDoughty** [facebook/pop#62]
I see that POPAnimations do not conform to NSCopying. I don't know enough about POP to say for certain, but I use relative additive Core Animation to get a similar effect as POP, and copying is a critical technique that might also be useful here.

If layers are already animating along a complicated path due to continuous user interaction, and you want to insert new layers with animated values that exactly match existing ones, copying is one way to accomplish this.

**Comment by johnboiles** [comment]
I'd use `NSCopying` slightly differently. I often have a handful of views/layers that I want to move in different ways using the same animation curve. Using `NSCopying` to copy a `POPAnimation` would save me the repetition of redefining the animation properties multiple times. Here's an example:

        POPSpringAnimation *anim1 = [POPSpringAnimation animation];
        anim1.property = [POPAnimatableProperty propertyWithName:kPOPViewFrame];
        anim1.toValue = [NSValue valueWithCGRect:rect1];
        anim1.springBounciness = 14;
        anim1.springSpeed = 20;
        anim1.beginTime = CACurrentMediaTime() + 0.1;
        [view1 pop_addAnimation:anim1 forKey:kPOPViewFrame];

        POPSpringAnimation *anim2 = [anim1 copy];
        anim2.toValue = [NSValue valueWithCGRect:rect2];
        [view2 pop_addAnimation:anim2 forKey:kPOPViewFrame];

        POPSpringAnimation *anim3 = [anim1 copy];
        anim3.property = [POPAnimatableProperty propertyWithName:kPOPViewAlpha];
        anim3.toValue = @1;
        [view3 pop_addAnimation:anim3 forKey:@"alpha"];

**Comment by grp** [comment]
You could make a function to configure the animation so you don't have to repeat it?

**Comment by johnboiles** [comment]
That's true. Or I could add `copyWithZone:` to `POPAnimation` and not have to create a function each time I want to reuse an animation's properties :)

If someone submitted the PR, would you accept it? Or is there another reason to avoid `NSCopying` in pop?

**Comment by grp** [comment]
The reason to avoid it is that Pop animations have state about the current progress for an animation. If an animation is in progress and you copy it, would it copy that state too? It's not immediately obvious, at least to me. But I'm not sure that's worth not supporting NSCopying — maybe @kimon has thoughts.

**Comment by johnboiles** [comment]
I don't think it'd make sense to copy anything related to the state of the animation. Most of the state is internal anyways right?

**Comment by crylico** [comment]
I've been playing with ComponentKit and have a working implementation (albeit simple) of POP working on components.

In `CKComponentAnimation`, `CAAnimation`s are copied to "prevent the caller from mutating the animation", which is a reason I'd like to implement `NSCopying` for `POPAnimation` and subclasses.

I was thinking that the `NSCopying` implementation could just copy public-facing API and leave the internal state at its initial state. This would work well for the above case and also for my use.

If it's not desirable to include this in the core project, I'd be happy to implement it and host it in another repository.

**Comment by grp** [comment]
Sounds great to me, will keep my eye out for a pull request!

**Comment by johnboiles** [comment]
Thanks @grp for confirming that you'd accept this. @crylico are you going to take a stab at this or should I?

**Comment by crylico** [comment]
Hey, @johnboiles I'm actually in the middle of this right now :) should have a pull request later this evening or early tomorrow

**Comment by johnboiles** [comment]
Thanks @crylico!
