### ISSUE TITLE
Spring with kPOPLayerScaleXY flips the image of UIImageView

### ISSUE THREAD

**Issue by JmeHsieh** [facebook/pop#76]
Weird thing is it only flips for the very first time when I triggered this animation.
Here is my code when UIImageView is tapped:

``` objective-c
- (void)buttonTapped:(id)sender
{
    id object = [sender view];

    POPSpringAnimation *spring = [POPSpringAnimation animationWithPropertyNamed:kPOPLayerScaleXY];
    spring.fromValue = [NSValue valueWithCGSize:CGSizeMake(0.8, 0.8)];
    spring.toValue = [NSValue valueWithCGSize:CGSizeMake(1, 1)];
    spring.springBounciness = 10;
    spring.springSpeed = 20;
    [object pop_addAnimation:spring forKey:@"anything"];
}
```

**Comment by mitchellporter** [comment]
@bbnnt I was able to fix this by setting my animation's ```clampMode``` property to ```kPOPAnimationClampEnd```. My animation was scaling a button's layer down to 0 and the spring must have caused the negative values.
